export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    const headers = { 'Access-Control-Allow-Origin': '*' }

    // Fetch world stats from worlds worker
    let worldsData = { total: 135, by_type: {}, recent: [] }
    try {
      const statsResp = await fetch('https://worlds.blackroad.io/stats')
      if (statsResp.ok) {
        const data = await statsResp.json()
        worldsData = data
      }
    } catch (e) {}

    if (url.pathname === '/feed.rss' || url.pathname === '/rss') {
      // Generate RSS 2.0 feed
      const items = generateRSSItems(worldsData)
      const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>BlackRoad OS Worlds</title>
    <link>https://worlds.blackroad.io</link>
    <description>Live world artifacts from BlackRoad OS Pi network (${worldsData.total} worlds generated)</description>
    <atom:link href="https://worlds-feed.blackroad.io/feed.rss" rel="self" type="application/rss+xml"/>
    <language>en-us</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    ${items}
  </channel>
</rss>`
      return new Response(rss, {
        headers: { ...headers, 'Content-Type': 'application/rss+xml; charset=utf-8' }
      })
    }

    if (url.pathname === '/feed.atom' || url.pathname === '/atom') {
      const entries = generateAtomEntries(worldsData)
      const atom = `<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>BlackRoad OS Worlds</title>
  <link href="https://worlds.blackroad.io"/>
  <link rel="self" href="https://worlds-feed.blackroad.io/feed.atom"/>
  <updated>${new Date().toISOString()}</updated>
  <id>https://worlds-feed.blackroad.io</id>
  <subtitle>Live world artifacts from BlackRoad OS Pi network — ${worldsData.total} worlds generated</subtitle>
  ${entries}
</feed>`
      return new Response(atom, {
        headers: { ...headers, 'Content-Type': 'application/atom+xml; charset=utf-8' }
      })
    }

    // Default: JSON stats + feed URLs
    const response = {
      worlds: worldsData.total,
      by_type: worldsData.by_type,
      feeds: {
        rss: 'https://worlds-feed.blackroad.io/feed.rss',
        atom: 'https://worlds-feed.blackroad.io/feed.atom'
      },
      generated_at: new Date().toISOString()
    }
    return new Response(JSON.stringify(response, null, 2), {
      headers: { ...headers, 'Content-Type': 'application/json' }
    })
  }
}

function generateRSSItems(worldsData) {
  const types = worldsData.by_type || {}
  const total = worldsData.total || 0
  const now = new Date()
  
  // Generate items from type counts
  const items = []
  const typeIcons = { world: '🌍', lore: '📖', code: '💻' }
  
  for (const [type, count] of Object.entries(types)) {
    const icon = typeIcons[type] || '🌌'
    items.push(`
    <item>
      <title>${icon} ${count} ${type} worlds generated</title>
      <link>https://worlds.blackroad.io</link>
      <description>BlackRoad OS has generated ${count} ${type}-type world artifacts across the Pi fleet. Total: ${total} worlds.</description>
      <pubDate>${now.toUTCString()}</pubDate>
      <guid>https://worlds.blackroad.io/${type}-${now.toDateString().replace(/ /g,'-')}</guid>
    </item>`)
  }
  
  // Add total summary item
  items.unshift(`
    <item>
      <title>🌌 ${total} worlds generated by BlackRoad OS</title>
      <link>https://worlds.blackroad.io</link>
      <description>BlackRoad OS Pi network has autonomously generated ${total} world artifacts using the world-engine. Generating ~1 world per minute per node.</description>
      <pubDate>${now.toUTCString()}</pubDate>
      <guid>https://worlds.blackroad.io/total-${total}</guid>
    </item>`)
  
  return items.join('\n')
}

function generateAtomEntries(worldsData) {
  const total = worldsData.total || 0
  const now = new Date().toISOString()
  return `
  <entry>
    <title>🌌 ${total} worlds generated by BlackRoad OS</title>
    <link href="https://worlds.blackroad.io"/>
    <id>https://worlds.blackroad.io/total-${total}</id>
    <updated>${now}</updated>
    <summary>BlackRoad OS Pi network has autonomously generated ${total} world artifacts.</summary>
  </entry>`
}
