/**
 * BlackRoad Worlds Feed Worker
 * Serves world artifacts from BlackRoad-OS-Inc/blackroad-agents
 */

const REPO = "BlackRoad-OS-Inc/blackroad-agents"
const GITHUB_API = "https://api.github.com"
const CACHE_TTL = 120

function parseWorldPath(path) {
  const m = path.match(/^([\w-]+)\/((\d{8})_(\d{6})_(world|lore|code)_(.+))\.md$/)
  if (!m) return null
  const [, dir, filename, date, time, type, slug] = m
  const node = dir === "worlds" ? "aria64" : dir.replace("-worlds", "")
  const ts = `${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}T${time.slice(0,2)}:${time.slice(2,4)}:${time.slice(4,6)}Z`
  return {
    id: filename,
    title: slug.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase()),
    node, type, path, timestamp: ts,
    link: `https://github.com/${REPO}/blob/main/${path}`,
  }
}

async function fetchWorlds(env) {
  const token = env.GITHUB_TOKEN
  const headers = {
    Accept: "application/vnd.github.v3+json",
    "User-Agent": "blackroad-worlds-worker"
  }
  if (token) headers.Authorization = `token ${token}`

  const url = `${GITHUB_API}/repos/${REPO}/git/trees/main?recursive=1`
  const res = await fetch(url, { headers })
  if (!res.ok) {
    const body = await res.text()
    throw new Error(`GitHub ${res.status}: ${body.slice(0,200)}`)
  }
  const tree = await res.json()

  return tree.tree
    .map(f => f.path)
    .filter(p => (p.startsWith("worlds/") || p.includes("-worlds/")) && p.endsWith(".md"))
    .map(parseWorldPath)
    .filter(Boolean)
    .sort((a, b) => b.timestamp.localeCompare(a.timestamp))
}

function rss(worlds) {
  const items = worlds.slice(0, 50).map(w => `
    <item>
      <title>${w.title} [${w.type}@${w.node}]</title>
      <link>${w.link}</link>
      <guid>${w.id}</guid>
      <pubDate>${new Date(w.timestamp).toUTCString()}</pubDate>
      <description>World artifact generated by ${w.node}</description>
    </item>`).join("")
  return `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel>
    <title>BlackRoad Worlds Feed</title>
    <link>https://worlds.blackroad.io</link>
    <description>AI-generated world artifacts from the BlackRoad fleet</description>
    ${items}
  </channel></rss>`
}

function atom(worlds) {
  const entries = worlds.slice(0, 50).map(w => `
  <entry>
    <id>urn:blackroad:world:${w.id}</id>
    <title>${w.title}</title>
    <link href="${w.link}"/>
    <updated>${w.timestamp}</updated>
    <author><name>${w.node}</name></author>
    <content type="text">Type: ${w.type}</content>
  </entry>`).join("")
  return `<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>BlackRoad Worlds</title>
  <id>https://worlds.blackroad.io/</id>
  <updated>${new Date().toISOString()}</updated>
  ${entries}
</feed>`
}

function feedHTML(worlds, stats) {
  const { total, by_node } = stats
  const aria64 = by_node.aria64 || 0
  const alice = by_node.alice || 0
  const worldListHTML = worlds.slice(0, 20).map(w => `
    <div class="world-item">
      <span class="type-${w.type}">[${w.type}]</span>
      <strong>${w.title}</strong>
      <span class="node">@${w.node}</span>
      <small style="color:#555">${w.timestamp.replace("T", " ").slice(0, 16)}</small>
    </div>`).join("")

  return `<!DOCTYPE html>
<html>
<head>
  <title>🌍 BlackRoad World Generator</title>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="10">
  <style>
    body { background: #000; color: #fff; font-family: monospace; padding: 2rem; max-width: 900px; margin: 0 auto; }
    h1 { color: #FF1D6C; margin-bottom: 0.5rem; }
    h2 { color: #F5A623; border-bottom: 1px solid #333; padding-bottom: 0.5rem; }
    .count { font-size: 4rem; color: #FF1D6C; font-weight: bold; line-height: 1; }
    .nodes { color: #aaa; margin-bottom: 1.5rem; }
    .nodes span { color: #F5A623; }
    .world-item { padding: 0.5rem; border-bottom: 1px solid #222; display: flex; gap: 0.75rem; align-items: baseline; flex-wrap: wrap; }
    .world-item:hover { background: #111; }
    .node { color: #F5A623; }
    .type-lore { color: #8B5CF6; }
    .type-world { color: #10A37F; }
    .type-code { color: #2979FF; }
    a { color: #2979FF; text-decoration: none; }
    a:hover { text-decoration: underline; }
    footer { margin-top: 2rem; color: #444; font-size: 0.8rem; }
  </style>
</head>
<body>
  <h1>🌍 BlackRoad World Generator</h1>
  <div class="count">${total}</div>
  <p>worlds generated</p>
  <p class="nodes"><span>${aria64}</span> aria64 | <span>${alice}</span> alice | ~2/min</p>
  <h2>Recent Worlds</h2>
  ${worldListHTML}
  <footer>Auto-refreshes every 10s · <a href="/stats">stats</a> · <a href="/rss">rss</a> · <a href="/recent?limit=20">recent JSON</a></footer>
</body>
</html>`
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    const path = url.pathname

    const corsHeaders = {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
    }

    if (request.method === "OPTIONS") {
      return new Response(null, { headers: corsHeaders })
    }

    const cache = caches.default
    const cacheKey = new Request(request.url)
    const cached = await cache.match(cacheKey)
    if (cached) return cached

    try {
      const worlds = await fetchWorlds(env)

      let response
      if (path === "/health") {
        response = new Response(JSON.stringify({
          status: "ok",
          total: worlds.length,
          timestamp: new Date().toISOString()
        }), {
          headers: { ...corsHeaders, "Content-Type": "application/json", "Cache-Control": "max-age=30" }
        })
      } else if (path === "/recent") {
        const limit = Math.min(parseInt(url.searchParams.get("limit") || "10", 10), 100)
        const recent = worlds.slice(0, limit).map(({ id, title, node, type, path }) => ({ id, title, node, type, path }))
        response = new Response(JSON.stringify({ worlds: recent, count: recent.length }, null, 2), {
          headers: { ...corsHeaders, "Content-Type": "application/json", "Cache-Control": `max-age=${CACHE_TTL}` }
        })
      } else if (path === "/feed") {
        const types = {}, nodes = {}
        for (const w of worlds) {
          types[w.type] = (types[w.type] || 0) + 1
          nodes[w.node] = (nodes[w.node] || 0) + 1
        }
        const stats = { total: worlds.length, by_type: types, by_node: nodes }
        response = new Response(feedHTML(worlds, stats), {
          headers: { ...corsHeaders, "Content-Type": "text/html;charset=UTF-8", "Cache-Control": `max-age=30` }
        })
      } else if (path === "/stats") {
        const types = {}, nodes = {}
        for (const w of worlds) {
          types[w.type] = (types[w.type] || 0) + 1
          nodes[w.node] = (nodes[w.node] || 0) + 1
        }
        response = new Response(JSON.stringify({
          total: worlds.length,
          by_type: types,
          by_node: nodes,
          generated_at: new Date().toISOString()
        }, null, 2), {
          headers: { ...corsHeaders, "Content-Type": "application/json", "Cache-Control": `max-age=60` }
        })
      } else if (path === "/rss") {
        response = new Response(rss(worlds), {
          headers: { ...corsHeaders, "Content-Type": "application/rss+xml", "Cache-Control": `max-age=${CACHE_TTL}` }
        })
      } else if (path === "/atom") {
        response = new Response(atom(worlds), {
          headers: { ...corsHeaders, "Content-Type": "application/atom+xml", "Cache-Control": `max-age=${CACHE_TTL}` }
        })
      } else if (path !== "/" && path.length > 1) {
        const id = path.slice(1)
        const world = worlds.find(w => w.id === id)
        if (!world) return new Response(JSON.stringify({ error: "Not found" }), { status: 404, headers: { "Content-Type": "application/json" } })
        response = new Response(JSON.stringify(world, null, 2), {
          headers: { ...corsHeaders, "Content-Type": "application/json" }
        })
      } else {
        const payload = { total: worlds.length, worlds: worlds.slice(0, 100), generated: new Date().toISOString() }
        response = new Response(JSON.stringify(payload, null, 2), {
          headers: { ...corsHeaders, "Content-Type": "application/json", "Cache-Control": `max-age=${CACHE_TTL}` }
        })
      }

      ctx.waitUntil(cache.put(cacheKey, response.clone()))
      return response
    } catch (e) {
      return new Response(JSON.stringify({ error: e.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" }
      })
    }
  }
}
