/**
 * BlackRoad Worlds Feed Worker
 * Serves world artifacts from BlackRoad-OS-Inc/blackroad-agents
 */

const REPO = "BlackRoad-OS-Inc/blackroad-agents"
const GITHUB_API = "https://api.github.com"
const CACHE_TTL = 120

function parseWorldPath(path) {
  const m = path.match(/^([\w-]+)\/((\d{8})_(\d{6})_(world|lore|code)_(.+))\.md$/)
  if (!m) return null
  const [, dir, filename, date, time, type, slug] = m
  const node = dir === "worlds" ? "aria64" : dir.replace("-worlds", "")
  const ts = `${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}T${time.slice(0,2)}:${time.slice(2,4)}:${time.slice(4,6)}Z`
  return {
    id: filename,
    title: slug.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase()),
    node, type, path, timestamp: ts,
    link: `https://github.com/${REPO}/blob/main/${path}`,
  }
}

async function fetchWorlds(env) {
  const token = env.GITHUB_TOKEN
  const headers = {
    Accept: "application/vnd.github.v3+json",
    "User-Agent": "blackroad-worlds-worker"
  }
  if (token) headers.Authorization = `token ${token}`

  const url = `${GITHUB_API}/repos/${REPO}/git/trees/main?recursive=1`
  const res = await fetch(url, { headers })
  if (!res.ok) {
    const body = await res.text()
    throw new Error(`GitHub ${res.status}: ${body.slice(0,200)}`)
  }
  const tree = await res.json()

  return tree.tree
    .map(f => f.path)
    .filter(p => (p.startsWith("worlds/") || p.includes("-worlds/")) && p.endsWith(".md"))
    .map(parseWorldPath)
    .filter(Boolean)
    .sort((a, b) => b.timestamp.localeCompare(a.timestamp))
}

function rss(worlds) {
  const items = worlds.slice(0, 50).map(w => `
    <item>
      <title>${w.title} [${w.type}@${w.node}]</title>
      <link>${w.link}</link>
      <guid>${w.id}</guid>
      <pubDate>${new Date(w.timestamp).toUTCString()}</pubDate>
      <description>World artifact generated by ${w.node}</description>
    </item>`).join("")
  return `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel>
    <title>BlackRoad Worlds Feed</title>
    <link>https://worlds.blackroad.io</link>
    <description>AI-generated world artifacts from the BlackRoad fleet</description>
    ${items}
  </channel></rss>`
}

function atom(worlds) {
  const entries = worlds.slice(0, 50).map(w => `
  <entry>
    <id>urn:blackroad:world:${w.id}</id>
    <title>${w.title}</title>
    <link href="${w.link}"/>
    <updated>${w.timestamp}</updated>
    <author><name>${w.node}</name></author>
    <content type="text">Type: ${w.type}</content>
  </entry>`).join("")
  return `<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>BlackRoad Worlds</title>
  <id>https://worlds.blackroad.io/</id>
  <updated>${new Date().toISOString()}</updated>
  ${entries}
</feed>`
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    const path = url.pathname

    const corsHeaders = {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
    }

    if (request.method === "OPTIONS") {
      return new Response(null, { headers: corsHeaders })
    }

    const cache = caches.default
    const cacheKey = new Request(request.url)
    const cached = await cache.match(cacheKey)
    if (cached) return cached

    try {
      const worlds = await fetchWorlds(env)

      let response
      if (path === "/stats") {
        const types = {}, nodes = {}
        for (const w of worlds) {
          types[w.type] = (types[w.type] || 0) + 1
          nodes[w.node] = (nodes[w.node] || 0) + 1
        }
        response = new Response(JSON.stringify({
          total: worlds.length,
          by_type: types,
          by_node: nodes,
          generated_at: new Date().toISOString()
        }, null, 2), {
          headers: { ...corsHeaders, "Content-Type": "application/json", "Cache-Control": `max-age=60` }
        })
      } else if (path === "/rss") {
        response = new Response(rss(worlds), {
          headers: { ...corsHeaders, "Content-Type": "application/rss+xml", "Cache-Control": `max-age=${CACHE_TTL}` }
        })
      } else if (path === "/atom") {
        response = new Response(atom(worlds), {
          headers: { ...corsHeaders, "Content-Type": "application/atom+xml", "Cache-Control": `max-age=${CACHE_TTL}` }
        })
      } else if (path !== "/" && path.length > 1) {
        const id = path.slice(1)
        const world = worlds.find(w => w.id === id)
        if (!world) return new Response(JSON.stringify({ error: "Not found" }), { status: 404, headers: { "Content-Type": "application/json" } })
        response = new Response(JSON.stringify(world, null, 2), {
          headers: { ...corsHeaders, "Content-Type": "application/json" }
        })
      } else {
        const payload = { total: worlds.length, worlds: worlds.slice(0, 100), generated: new Date().toISOString() }
        response = new Response(JSON.stringify(payload, null, 2), {
          headers: { ...corsHeaders, "Content-Type": "application/json", "Cache-Control": `max-age=${CACHE_TTL}` }
        })
      }

      ctx.waitUntil(cache.put(cacheKey, response.clone()))
      return response
    } catch (e) {
      return new Response(JSON.stringify({ error: e.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" }
      })
    }
  }
}
